
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using IdentityServer.Application.Features.Auth.Commands.Login;
using MediatR;

namespace IdentityServer.Application.Features.Users.Commands.Update;

public class UpdateUserCommand : IRequest<LoginResponse>
{
    public Guid Id { get; set; }
    public string? DeviceId { get; set; }
    public string? DeviceToken { get; set; }
    public string UserName { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string PhoneNumber { get; set; }
    public string NormalizedMailAddress => MailAddress.ToLower();
    public string MailAddress { get; set; }
    public bool AgreeContact { get; set; }

}




