
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using MediatR;

namespace IdentityServer.Application.Features.Users.Commands.Create;

public class CreateUserCommand : IRequest<CreateUserResponse>  
{

    public string? DeviceId { get; set; }
    public string? DeviceToken { get; set; }
    public string? CompanyName { get; set; }
    public string PhoneNumber { get; set; }
    public string LastName { get; set; }
	public string UserName { get; set; }
	public string NormalizedMailAddress => MailAddress.ToLower();
	public string MailAddress { get; set; }
	public string NormalizedUserName => UserName.ToLower();
	public string FirstName { get; set; }
	public Guid Id { get; set; }
	public int Status { get; set; }
    public string Password { get; set; }
    public bool AgreeContact { get; set; }
    public TimeSpan Offset { get; set; }
    public string Language { get; set; }
}




